// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library.Mvc.Models
{
    public partial class BorrowedBook
    {
        public int BorrowId { get; set; }
        public DateTime BorrowDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public int? BookId { get; set; }
        public int? UserId { get; set; }

        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}